### ISSUE TITLE
Prison RP (CRISIS)

### ISSUE THREAD

**Issue by iDulvious** [ChainedDev/CityLife#160] opened 2020-04-29 17:10 UTC
They should upgrade the prison system. If you go to prison there is nothing to do. Allow people to go to the court yard and get a prison job to earn a bit of money. Add prison guards that patrol the court yards. Prison should have Prison RP. All I see when im pinched is people going AFK in their cells and its really boring.

**Comment by Wizmex** [comment] 2020-04-29 19:08
This would indeed add a very big and nice aspect of RP to citylife!

**Comment by ChainedDev** [comment] 2020-04-29 19:13
Follow the template please

**Comment by ChainedDev** [comment] 2020-05-07 20:20
Duplicate of #32

**Closed by ChainedDev** 2020-05-07 20:20 UTC
Labels: Suggestion
