### ISSUE TITLE
Feature Request: Holding F to Respawn.

### ISSUE THREAD

**Issue by CustomChance** [ChainedDev/CityLife#811] opened 2021-08-14 17:26 UTC
**Is your feature request related to a problem? Please describe.**
Yes, The problem is that people accidentally press f while dead and lose all of their items.

**Describe the feature you'd like**
Instead of just tapping F after waiting 300 seconds you should make it so you have to hold down F for 5 seconds to respawn this is to prevent people from accidentally pressing f and losing there items ( Happened to me before)

**Describe alternatives you've considered**
When pressing F make it show a prompt to Continue and respawn or to stop the respawning.

**Additional context**
(Blank)

**Comment by Chainedster** [comment] 2022-05-11 06:41
👀

**Comment by Chainedster** [comment] 2022-05-11 07:06
Duplicate of #231

**Closed as completed by Chainedster** 2022-05-11 07:06 UTC
Labels: Suggestion
