### ISSUE TITLE
new PD

### ISSUE THREAD

**Issue by Callum0202** [ChainedDev/CityLife#236] opened 2020-07-01 21:52 UTC
https://www.gta5-mods.com/maps/police-station-mission-row-exterior-modded-fivem-sp-menyoo-ymap-xml

**Comment by TheLitteralIcemanStraightOuttaFinlandia** [comment] 2020-07-02 00:08
My friend, there is no need to change the PD look, it's beautiful as it is. This looks like old snus I've reused 15 times. 
Best regards Mr iceman

**Comment by Skader91** [comment] 2020-07-02 16:13
Disregard Iceman, Acquire new sweet ass PD

**Comment by Skader91** [comment] 2020-07-02 16:14
This is outside only though, I highly recommend one that has a interior like this.
https://www.gta5-mods.com/maps/community-mission-row-pd

**Comment by ChainedDev** [comment] 2020-07-03 17:23
Duplicate of #161 please put suggestions on the existing topic please

**Closed by ChainedDev** 2020-07-03 17:23 UTC
Labels: Suggestion
