### ISSUE TITLE
Exiting a vehicle when you didn't intend to

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#127] opened 2020-04-05 19:23 UTC
**Describe the bug**
Currently there is a bug where when you enter a vehicle you have a small chance of getting out.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Get in Vehicle, Cry as you get out of vehicle

**Expected Behaviour**
Staying in the vehicle

**Additional context**
I believe it's related to being able to shoot out of vehicles since it only started when that was introduced. It makes someone taking off on cops during a traffic stop real annoying when you go to take off after them and you just hop out.

**Comment by ChainedDev** [comment] 2020-06-01 00:10
Still persisting?

**Comment by ChainedDev** [comment] 2020-07-03 17:20
Duplicate of #106

**Closed by ChainedDev** 2020-07-03 17:20 UTC
Labels: Bug
