### ISSUE TITLE
Adding a way to place downed friend in a car seat to take them to hospital by yourself 

### ISSUE THREAD

**Issue by DeezNipzz** [ChainedDev/CityLife#316] opened 2020-08-03 11:07 UTC
**Is your feature request related to a problem? Please describe.**
Since the only option is to carry we can't carry them and drive. It would be nice to be able to place them in a seat and then drive them to hospital. 

**Describe the feature you'd like**
Ability to place downed friend in a seat in the car and drive them to hospital without needing another person to drive you.

**Describe alternatives you've considered**
Cant think of any alternatives other than just placing them in the open seat. Unless we were allowed to carry them and drive and just imagine that realistically they would be in the passenger seat.

**Additional context**
none

**Comment by ChainedDev** [comment] 2020-08-08 05:06
Duplicate of #256 feature will be coming, just need the right time to get it done in

**Closed by ChainedDev** 2020-08-08 05:06 UTC
Labels: Suggestion
