### ISSUE TITLE
Garages 

### ISSUE THREAD

**Issue by EvaLaura69** [ChainedDev/CityLife#325] opened 2020-08-10 11:09 UTC
Add personal garages to properties. It seems normal to take your car from your garage rather than from a public space. 

**Describe the feature you'd like**
Have personal garages to owned houses. 

**Describe alternatives you've considered**
No alternatives

**Additional context**
This will also fix the problem with rdm in the Legion garage.

**Comment by ChainedDev** [comment] 2020-12-08 04:26
Duplicate of #157 moving there

**Closed by ChainedDev** 2020-12-08 04:26 UTC
Labels: Suggestion
