### ISSUE TITLE
NoPixel Chat Looks attractive and CLRP deserves Beauty

### ISSUE THREAD

**Issue by strangeclrpindia** [ChainedDev/CityLife#77] opened 2020-02-18 19:34 UTC
**Is your feature request related to a problem?
No

Describe the feature you'd like
Its NoPixel Chat , is very attractive and CityLife Roleplay deserves the beauty. The only thing needs to get updated in CityLife RP is this chat. It would look more professional. Also a well maintained healthbar with stamina, hunger with voice range will provide server a fabulous look.

![image](https://user-images.githubusercontent.com/60332040/74770977-59f3e080-52b3-11ea-91a6-5b2ace360f6f.png)

![image](https://user-images.githubusercontent.com/60332040/74770994-611aee80-52b3-11ea-9348-fae8d71aa23f.png)

**Comment by ChainedDev** [comment] 2020-02-20 16:45
Duplicate of #66

**Closed by ChainedDev** 2020-02-20 16:45 UTC
Labels: Suggestion
