### ISSUE TITLE
Please add /carry, much needed

### ISSUE THREAD

**Issue by strangeclrpindia** [ChainedDev/CityLife#76] opened 2020-02-18 19:29 UTC
**What is the reason for this balance request?**
The thing is we can't carry someone and take to pillbox when there is no police and ems. Also Every-time Spawning results in mugged up things every-time. 

**What solution would you like?**
We can add /carry command for all , so that it enhances role-play and it can solve 90% of the problem.

If need help, here's /carry script:
https://github.com/rubbertoe98/FiveM-Scripts/tree/master/CarryPeople

**Comment by gavisuprstar** [comment] 2020-02-19 23:35
@ChainedDev @gullidog i guess this may help you in this 

https://forum.cfx.re/t/release-carry-people-over-your-shoulder/788958

**Comment by gavisuprstar** [comment] 2020-02-19 23:37
It will be great if you can add to put a person in car truck while carry and while near a cars trunk.

**Comment by ChainedDev** [comment] 2020-02-19 23:43
Clydo said he didn't like that one but we've been keeping an eye on it but haven't gotten the time implement it properly, along with the ability to put someone in a trunk, we need to get our old 'hiding in trunk' system improved first and tell clydo to behave and should be in 🔜

**Comment by ChainedDev** [comment] 2020-02-20 16:45
Duplicate of #47

**Closed by ChainedDev** 2020-02-20 16:45 UTC
Labels: Balance, In-Progress

**Comment by strangeclrpindia** [comment] 2020-02-20 20:05
Demand 100% 
Much needed
