### ISSUE TITLE
Tow Truck Whitelisted Job

### ISSUE THREAD

**Issue by Satan-5638** [ChainedDev/CityLife#73] opened 2020-02-18 02:09 UTC
Having a Tow Service or Vehicle Recovery Service as a new whitelisted job.

There could be varying degrees of tow trucks, heavy tow trucks for transports and other commercial vehicles, flat bed tow trucks, and they normal smaller tow truck. They could do car unlocks for people using a slim jim tool or just lockpicks upon request. There could be tow truck missions to go and tow cars illegally parked or broken down cars. Then players could request to have there vehicle(s) towed to a garage or to a lot of there choosing and have to explain the issue and the operator would bring whichever tow truck they felt was best for the job description. The police may need certain vehicles towed depending on the situations at hand eg. car crash, owner/driver was arrested, etc.

For the missions you get so much based on what kind of vehicles you tow back to the impound lot, for players they pay you based upon a set rate, for the police calls there could be some kind of callout system and the tow operator gets paid from that.

**Comment by ChainedDev** [comment] 2020-02-20 16:41
Duplicate of #68

**Closed by ChainedDev** 2020-02-20 16:41 UTC
Labels: Suggestion
