### ISSUE TITLE
People and Cars

### ISSUE THREAD

**Issue by Cele121** [ChainedDev/CityLife#510] opened 2021-01-01 15:01 UTC
Ok so basically I would like it if you could place people that have died into a car. You already have the "Z" menu and can unseat/seat people in cars. Why cant we seat someone who has been downed into a car without them falling out? Also, it would be nice for hostage situations to be able to place people into the trunks of cars. Are these things that could be done?

**Comment by Chainedster** [comment] 2021-02-25 01:02
Duplicate of #379 do you guys even check if something has been suggested/in-progress before posting?

**Closed by Chainedster** 2021-02-25 01:02 UTC
Labels: Suggestion
