### ISSUE TITLE
An additional reviving method, due to lack of medics.

### ISSUE THREAD

**Issue by Jxcob** [ChainedDev/CityLife#54] opened 2020-01-20 23:43 UTC
**Is your feature request related to a problem? Please describe.**
Yes, when there are no medics on, which is 24/7 during UK times, there is literally no way to help yourself up.

**Describe the feature you'd like**
The ability to purchase a defibrillator from either a hospital or some sort of shop to revive your friends with.

**Additional context**
Obviously, you can't use the defibrillator yourself, but you have to have someone else use it on you.

**Comment by ChainedDev** [comment] 2020-01-26 22:15
If you go to the hospital and hit E while dead it will check you in then revive, we're waiting to implement a carry feature so friends would be able to assist you instead of having you stuck there, needs proper implementation then should be fully ready

**Comment by ChainedDev** [comment] 2020-01-26 22:17
Duplicate of #47

**Closed by ChainedDev** 2020-01-26 22:17 UTC
Labels: Suggestion
