### ISSUE TITLE
Adding Trunks to Boats

### ISSUE THREAD

**Issue by JooniJunebug** [ChainedDev/CityLife#428] opened 2020-11-09 17:05 UTC
**Is your feature request related to a problem? Please describe.**
Not exactly, you guys said recently you were reworking trunks didn't know if this was apart of the plan.
**Describe the feature you'd like**
Trunks Added to Boats
**Describe alternatives you've considered**
Making the Glovebox's bigger and renamed to *Trunks*

**Additional context**
I think adding Trunks to boats would change up the way fishing works and encourage people to buy boats.

**Comment by ChainedDev** [comment] 2020-11-09 17:40
Duplicate of #386

**Closed by ChainedDev** 2020-11-09 17:40 UTC
Labels: Suggestion
