### ISSUE TITLE
Create an App for Mechanic Items

### ISSUE THREAD

**Issue by MikeBrowni3** [ChainedDev/CityLife#586] opened 2021-02-21 03:10 UTC
**Is your feature request related to a problem? 

Kind of. When you buy a car in the server you can not see what items you can buy for your car unless a Mechanic is online. 

**Describe the feature you'd like**

Like to see an App on you phone that would link to your cars and allow you to scroll threw all the options to customize your car. Alot of times the Mechanics are not online. Be cool to scroll threw the app and see what the items will be and costs of them. So you know how much to saved up for. 

**Describe alternatives you've considered**

Other option would be allow us to use Bennys and look at all the items or allow the Salesmen at PDM to Customize the cars in the showroom to show you want you could do with your car.

**Comment by Chainedster** [comment] 2021-02-25 00:57
Duplicate of #538

**Closed as completed by Chainedster** 2021-02-25 00:57 UTC
Labels: Suggestion
